FROM node:18-slim

# Instalar curl
RUN apt-get update && apt-get install -y curl && apt-get clean

WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY src/backend ./src/backend

EXPOSE 3000
CMD ["node", "/app/src/backend/server.js"]
